---

- hosts: HOSTNAME 
  become: true
  become_user: root
  tasks:
  - user:
      name: ansible
      groups: "sudo"
      password: SHA-512(PASSWORD) 
  - name: Add key
    authorized_key: 
      user: ansible
      state: present
      key: "{{ lookup('file','KEYDIRECTORY')}}"
