---
# Written by Caleb Riggs
# Details:
#   This playbook will deploy a config from the controllers root/ansiConfig/config folder
#   to the remote hosts /etc/syslog-ng and /opt/splunk-syslog.
#
# Runtime:
#   To run on this VM simply sudo ansible-playbook deployConfig.yml -K
#

# sync info to targets
- hosts: test
  gather_facts: no
  # becuase of permissions in /opt and /etc requires root
  become: true
  become_user: root
  tasks: 
  - synchronize:
      mode: push
      owner: no
      dest: /opt/
      src: /root/ansiConfig/config/splunk-syslog
  - synchronize:
      mode: push
      owner: no
      dest: /etc/
      src: /root/ansiConfig/config/syslog-ng
